## __📌 What is a Tensor?__
__Definition:__ A tensor is a generalized multi-dimensional array that stores numerical data. It's the standard way to represent data in neural networks and deep learning frameworks.

__Analogy:__

+ Scalar = Single number (0D tensor)

+ Vector = List of numbers (1D tensor)

+ Matrix = Table of numbers (2D tensor)

+ Tensor = All of the above, extended to N dimensions

## __🔄 Tensor Dimensions with NumPy Examples__

__zero (0) D Tensor (scaler)__

In [ ]:
import numpy as np

a = np.array(4)
print(f"this is the value of this array {a}")
print(a)

print(f"The Dimension of this array is {np.ndim(a)}")
print(f"The shape of this array is {np.shape(a)}")
print(f"The rank of this array is {a.ndim}")

this is the value of this array 4
4
The Dimension of this array is 0
The shape of this array is ()
The rank of this array is 0


## __1D Tensor (Vector)__

+ 1 D tensor is a vector
+ And this below example of tensor have 5D vector 

+ Real life example of 1 D tensor  
+ house_features = [1200, 3, 10, 5]
+ ✅ That’s a 1D tensor (vector) representing one house.

In [7]:
vector = np.array([1,2,3,4,5])
vector
print(f"this is the value of this array {vector}")
print(vector)

print(f"The Dimension of this array is {np.ndim(vector)}")
print(f"The shape of this array is {np.shape(vector)}")
print(f"The rank of this array is {vector.ndim}")

this is the value of this array [1 2 3 4 5]
[1 2 3 4 5]
The Dimension of this array is 1
The shape of this array is (5,)
The rank of this array is 1


## __2 D Tensor / Matrices__

+ Real life example of 2 D tensor A 2D tensor in ML represents your entire dataset — where each row is one example and each column is one feature.  
+ ([
+    [1200, 3, 10, 5, 1500000],
+    [1500, 4, 8, 3, 1800000],
+    [800, 2, 20, 10, 1000000],
+    [950, 2, 15, 8, 1200000]
+ ])

In [9]:
sd = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
sd

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
print('rank of this array - ',sd.ndim)


rank of this array -  2


In [15]:
print('shape of the array is ',np.shape(sd))

shape of the array is  (3, 3)


In [16]:
print("Dimension of the array is -",np.ndim(sd))

Dimension of the array is - 2


## __3 D Tensor__

+ A 3D tensor is used when data has height, width, and depth  (or channels) —
+ like color images, videos, or time-series data across multiple sensors. Real life example of 3 D tensor  Image shape = (Height, Width, Channels)
+ Example: (64, 64, 3)

In [18]:
td = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,9,8]]])

In [21]:
print('3D arry is \n',td)

3D arry is 
 [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 9 8]]]


In [22]:
print('rank of this array is - ',td.ndim)

rank of this array is -  3


In [23]:
print('Dimension of this array is - ',np.ndim(td))

Dimension of this array is -  3


In [24]:
print('shape of the arrya is ',np.shape(td))

shape of the arrya is  (2, 2, 3)
